<?php
namespace App\Modules\Auth\Controllers;

use App\Web\Controllers\BaseController;
use App\Modules\Auth\Services\AuthService;
use App\Core\Database\Connection;
use Exception;

class RegisterController extends BaseController {
    private $authService;

    public function __construct() {
        $database = Connection::getInstance();
        $this->authService = new AuthService($database->getConnection());
    }

    public function store() {
        return $this->index(); // Handle POST in index method
    }

    public function index() {
        if (session_status() === PHP_SESSION_NONE) {
            session_start();
        }

        $error = '';
        $success = '';
        $formData = [];

        if ($_SERVER['REQUEST_METHOD'] === 'POST') {
            $formData = [
                'username' => trim($_POST['username'] ?? ''),
                'email' => trim($_POST['email'] ?? ''),
                'full_name' => trim($_POST['full_name'] ?? ''),
                'university' => $_POST['university'] ?? '',
                'role' => $_POST['role'] ?? ''
            ];

            if ($_POST['password'] !== $_POST['confirm_password']) {
                $error = "Passwords do not match.";
            } elseif (strlen($_POST['password']) < 6) {
                $error = "Password must be at least 6 characters long.";
            } elseif (!filter_var($formData['email'], FILTER_VALIDATE_EMAIL)) {
                $error = "Please enter a valid email address.";
            } elseif (empty($formData['username']) || empty($formData['full_name']) || empty($formData['university']) || empty($formData['role'])) {
                $error = "Please fill out all required fields.";
            } else {
                $result = $this->authService->register(
                    $formData['username'],
                    $formData['email'],
                    $_POST['password'],
                    $formData['full_name'],
                    $formData['university'],
                    $formData['role']
                );

                if ($result['success']) {
                    $success = 'Registration successful! You can now login.';
                    $formData = [];
                } else {
                    $error = $result['message'] ?? 'Registration failed. Username or email may already exist.';
                }
            }
        }

        /**
         * Link: https://www.unirank.org/ph/a-z/
         */
        // Nested Array
        $universities = [
            'University of the Philippines' => [
                'Abra State Institute of Science and Technology',
                'Adamson University',
                'Adamson University of the Philippines',
                'Aklan State University',
                'AMA Computer University',
                'Angeles University Foundation',
                'Aquinas University of Legazpi',
                'Araullo University',
                'Arellano University',
                'Ateneo de Manila University',
                'Ateneo de Naga University',
                'Ateneo de Davao University',
                'Ateneo de Zamboanga University',
                'Baguio Central University',
                'Baliuag University',
                'Bataan Peninsula State University Main Campus (Capitol Compound)',
                'Bataan Peninsula State University in Abucay',
                'Bataan Peninsula State University in Balanga',
                'Bataan Peninsula State University Dinalupihan Campus',
                'Bataan Peninsula State University in Orani',
                'Batangas State University',
                'Batangas State University - Gov.Pablo Borbon Campus I, Rizal ave., Batangas City',
                'Batangas State University - Gov.Pablo Borbon Campus II, Alangilan, Batangas City',
                'Batangas State University - ARASOF Campus - Nasugbu, Batangas',
                'Batangas State University - JPLPC Campus - Malvar, Batangas',
                'Batangas State University - Don Claro M. Recto Campus - Lipa City, Batangas',
                'Batangas State University - Lemery Campus',
                'Batangas State University - Balayan Campus',
                'Batangas State University - Lobo Campus',
                'Batangas State University - Rosario Campus',
                'Batangas State University - San Juan Campus',
                'Batangas State University - Taysan Campus',
                'Bicol University',
                'Bicol University Main Campus, Legazpi City, Albay',
                'Bicol University East Campus, Legazpi City',
                'Bicol University Daraga Campus, Daraga, Albay',
                'Bicol University Tabaco Campus, Tabaco City, Albay',
                'Bicol University Guinobatan Campus, Guinobatan, Abay',
                'Bicol University Polangui Campus, Polangui, Albay',
                'Bicol University Gubat Campus, Gubat, Sorsogon',
                'Bulacan State University Malolos Main Campus',
                'Bulacan State University Bustos Campus',
                'Bulacan State University Meneses Campus',
                'Bulacan State University Sarmiento Campus',
                'Bulacan State University Hong Kong Office',
                'Bulacan State University Hagonoy Campus',
                'Bulacan Agricultural State College',
                'Bukidnon State University Main Campus, Malaybalay City, Bukidnon',
                'Bukidnon State University - MOGHS External Studies Center, Cagayan de Oro City',
                'Bukidnon State University External Studies Center, Alubijid, Misamis Oriental',
                'Bukidnon State University External Studies Center, Gingoog City',
                'Bukidnon State University External Studies Center, Manolo Fortich, Bukidnon',
                'Bukidnon State University External Studies Center, Manticao, Misamis Oriental',
                'Bukidnon State University External Studies Center, Maragusan, Compostela Valley',
                'Bukidnon State University External Studies Center, Initao, Misamis Oriental',
                'Bukidnon State University External Studies Center, Libertad, Misamis Oriental',
                'Bukidnon State University External Studies Center, Sto. Tomas, Davao del Norte',
                'Cagayan State University Gonzaga Campus - Main Campus',
                'Cagayan State University - Carig Campus',
                'Cagayan State University - Caritan Campus',
                'Cagayan State University - Lallo Campus',
                'Cagayan State University - Piat Campus',
                'Cagayan State University - Aparri Campus',
                'Cagayan State University - Sanchez Mira Campus',
                'Cagayan State University - Lasam Campus',
                'Capitol University - Corrales Ext., Cagayan de Oro City',
                'Capiz State University - Roxas City Main Campus',
                'Capiz State University - Sigma Campus',
                'Capiz State University - Pontevedra Campus',
                'Capiz State University - Mambusao Campus',
                'Capiz State University - Dumarao Campus',
                'Capiz State University - Tapaz Campus',
                'Capiz State University - Pilar Campus',
                'Caraga State University',
                'Catanduanes State Colleges',
                'Cavite State University Main Campus (Don Severino de las Alas) Indang',
                'Cavite State University - Imus Campus (College of Business and Entrepreneurship)',
                'Cavite State University - Rosario Campus (College of Trade and Arts)',
                'Cavite State University - Carmona Campus',
                'Cavite State University - Silang Campus',
                'Cavite State University - Bacoor Campus',
                'Cavite State University - Naic Campus (College of Fisheries)',
                'Cavite State University - Trece Martires City Campus',
                'Cavite State University - Tanza Campus',
                'Cavite West Point College, Ternate',
                'Cebu Doctors University - Mandaue City',
                'Central Bicol State University of Agriculture - Pili Main Campus (formerly CSSAC-Pili)',
                'Central Bicol State University of Agriculture - Sipocot Campus (formerly CSSAC-Sipocot)',
                'Central Bicol State University of Agriculture - Sipocot Campus - Libmanan Extension Campus',
                'Central Bicol State University of Agriculture - Calabanga Campus (formerly Calabanga Polytechnic College)',
                'Central Philippine University - Jaro, Iloilo City',
                'Central Mindanao University',
                'Don Mariano Marcos Memorial State University',
                'Don Mariano Marcos University',
                'Eastern Samar State University - Borongan City Main Campus',
                'Eastern Samar State University - Can-Avid',
                'Eastern Samar State University - Guiuan',
                'Eastern Samar State University - Maydolong',
                'Eastern Samar State University - Salcedo',
                'Eastern Visayas State University - Tacloban City Main Campus',
                'Eastern Visayas State University - Ormoc City Satellite Campus',
                'Eastern Visayas State University - Tanauan External Campus',
                'Eastern Visayas State University - Carigara External Campus',
                'Eastern Visayas State University - Burauen External Campus',
                'Eastern Visayas State University - Dulag External Campus',
                'Eastern Visayas State University - Pinabacdao',
                'Far Eastern University',
                'Fr. Saturnino Urios University',
                'FEATI University',
                'Foundation University, Dumaguete City',
                'Filamer Christian University, Roxas Avenue, Roxas City, Capiz',
                'Holy Angel University',
                'Holy Name University (formerly Divine Word College of Tagbilaran)',
                'Ifugao State University (Lamut, Ifugao)',
                'Jose Rizal Memorial State University',
                'Jose Rizal Memorial State University - Dipolog City Campus',
                'Jose Rizal Memorial State University - Dapitan City Campus',
                'Jose Rizal Memorial State University - Tampilisan Campus',
                'Jose Rizal Memorial State University - Siocon Campus',
                'Jose Rizal Memorial State University - Katipunan Campus',
                'Jose Rizal University',
                'La Consolacion University Philippines',
                'Laguna State Polytechnic University - Santa Cruz (Main Campus)',
                'Laguna State Polytechnic University - Los Banos',
                'Laguna State Polytechnic University - San Pablo City',
                'Laguna State Polytechnic University - Siniloan',
                'Laguna University - Sta. Cruz, Laguna',
                'Lyceum of the Philippines University',
                'Lyceum of the Philippines University - Manila - Intramuros, Manila',
                'Lyceum of the Philippines University - Batangas - Batangas City',
                'Lyceum of the Philippines University - Laguna - Calamba City, Laguna',
                'Lyceum of the Philippines University - Cavite - General Trias, Cavite',
                'Lyceum of the Philippines University Law School - Makati City',
                'Lyceum - St. Cabrini College of Allied Medicine - Sto. Tomas, Batangas',
                'Manila Central University',
                'Manuel L. Quezon University',
                'Mariano Marcos State University',
                'Manuel S. Enverga University Foundation - Lucena City, Quezon',
                'Manuel S. Enverga University Foundation - Catanauan, Quezon',
                'Manuel S. Enverga University Foundation - San Antonio, Quezon',
                'Manuel S. Enverga University Foundation - Candelaria, Quezon',
                'Manuel S. Enverga University Foundation - Sampaloc, Quezon',
                'Manuel S. Enverga University Foundation College of Law - Lucena City, Quezon',
                'Mindanao University of Science and Technology - Lapasan, Cagayan de Oro City',
                'Mindanao State University',
                'Mindanao State University - Marawi',
                'Mindanao State University - General Santos',
                'Mindanao State University - Sulu',
                'Mindanao State University - Maguindanao',
                'Mindanao State University - Naawan',
                'Mindanao State University - Tawi-Tawi',
                'Mindanao State University - Iligan Institute of Technology',
                'Misamis University',
                'Notre Dame of Dadiangas University',
                'Northwestern University (Philippines), Laoag City',
                'National University (Philippines)',
                'Negros Maritime College Foundation, Inc.',
                'Negros Oriental State University',
                'Negros Oriental State University - Main Campus 1, Dumaguete City',
                'Negros Oriental State University - Main Campus 2, Dumaguete City',
                'Negros Oriental State University - Guihulngan Campus',
                'Negros Oriental State University - Bais Campus 1',
                'Negros Oriental State University - Bais Campus 2',
                'Negros Oriental State University - Bayawan-Sta. Catalina Campus',
                'Negros Oriental State University - Siaton Campus',
                'Negros Oriental State University - Pamplona Farm',
                'Negros Oriental State University - Mabinay Campus',
                'New Era University',
                'New Era University, Quezon City',
                'New Era University, Pampanga',
                'New Era University, Batangas',
                'New Era University, General Santos City',
                'Our Lady of Fatima University',
                'Our Lady of Fatima University, Valenzuela City',
                'Our Lady of Fatima University, Quezon City',
                'Our Lady of Fatima University, Antipolo City',
                'Our Lady of Fatima University, City of San Fernando, Pampanga',
                'Panpacific University North Philippines, Urdaneta City',
                'Panpacific University North Philippines, Tayug',
                'Pangasinan State University',
                'Pangasinan State University - Graduate School',
                'Pangasinan State University - Asingan',
                'Pangasinan State University - Bayambang',
                'Pangasinan State University - Binmaley',
                'Pangasinan State University - Infanta',
                'Pangasinan State University - San Carlos City',
                'Pangasinan State University - Sta. Maria',
                'Pangasinan State University - Urdaneta City',
                'Pangasinan State University - Lingayen',
                'Polytechnic University of the Philippines',
                'Pilgrim University - Cagayan de Oro City',
                'Quezon City Polytechnic University',
                'Quezon City Polytechnic University, San Bartolome',
                'Quezon City Polytechnic University, Batasan Hills',
                'Quezon City Polytechnic University, San Francisco',
                'Rizal Technological University',
                'Rizal Technological University, Mandaluyong City',
                'Rizal Technological University, Pasig City',
                'Romblon State University',
                'Romblon State University Odiongan - Main Campus',
                'Romblon State University Romblon - Sawang Campus',
                'Romblon State University Tablas - Romblon College of Fisheries and Forestry, San Agustin Campus',
                'Romblon State University Tablas - Romblon College of Fisheries and Forestry, San Andres Campus',
                'Romblon State University Tablas - Santa Maria Campus',
                'Romblon State University Tablas - Santa Fe Campus',
                'Romblon State University Sibuyan - Cajidiocan Campus',
                'Romblon State University Sibuyan - Sibuyan Polytechnic College, San Fernando Campus',
                'Ramon Magsaysay Technological University Zambales',
                'Ramon Magsaysay Technological University - Main Campus, Iba, Zambales',
                'Ramon Magsaysay Technological University - San Marcelino Campus',
                'Ramon Magsaysay Technological University - Botolan Campus',
                'Ramon Magsaysay Technological University - Castillejos Campus',
                'Ramon Magsaysay Technological University - Masinloc Campus',
                'Ramon Magsaysay Technological University - Candelaria Campus',
                'Ramon Magsaysay Technological University - Sta. Cruz Campus',
                'University of the Samar Island Archipelago Catbalogan City Main Campus)',
                'University of the Samar Island Archipelago - Pinabacdao (South Samar Campus)',
                'University of the Samar Island Archipelago - Basey',
                'University of the Samar Island Archipelago - Paranas',
                'University of the Samar Island Archipelago - Mercedes, Catbalogan City',
                'University of the Samar Island Archipelago - Guiuan, Eastern Samar',
                'University of the Samar Island Archipelago - Catarman, Northern Samar',
                'Saint Louis University, Baguio City Main Campus - Bonifacio St., Baguio City',
                'Navy Base Campus - Navy Base, Baguio City',
                'Maryheights Campus - Bakakeng, Baguio City',
                'Gonzaga Campus - General Luna St., Baguio City',
                'St. Linus University (St Linus Online Institute) - Paniqui, Tarlac',
                "Saint Mary's University of Bayombong, Nueva Vizcaya",
                "Saint Mary's University of Cebu - Cebu City",
                'St. Mary\'s College of Boac - Marinduque',
                'St. Mary\'s College of Baliuag - Bulacan',
                'St. Mary\'s College of Borongan - Eastern, Samar',
                'St. Mary\'s College of Tagum - Tagum City, Davao',
                'St. Mary\'s College of Toledo - Toledo City, Cebu',
                'St. Mary\'s College of Labason - Labason, Zamboanga del Norte',
                'Silliman University, Dumaguete City',
                'Southern Leyte State University - Main Campus, Sogod, Southern Leyte',
                'Southern Leyte State University - Tomas Oppus Campus, San Isidro, Southern Leyte',
                'Southern Leyte State University - Bontoc Campus, San Ramon, Bontoc, Southern Leyte',
                'Southern Leyte State University - San Juan Campus, Southern Leyte',
                'Southern Leyte State University - Hinunangan Campus, Hinunangan, Southern Leyte',
                'Southern Luzon State University',
                'Taguig City University',
                'Tarlac State University',
                'Tarlac State University - San Vicente Campus',
                'Tarlac State University - San Isidro Campus',
                'Tarlac State University - Lucinda Campus',
                'United Doctors Medical Center - Southeast Asian College',
                'Universidad de Zamboanga',
                'University of Antique Sibalom, Antique',
                'University of Antique Tibiao, Antique',
                'University of Antique Hamtic, Antique',
                'University of Asia and the Pacific, Ortigas Center, Pasig City',
                'University of Baguio',
                'University of Batangas',
                'University of Bohol',
                'University of Cagayan Valley (Cagayan Colleges Tuguegarao)',
                'University of Caloocan City',
                'University of Cebu - Main Campus',
                'University of Cebu - Banilad Campus',
                'University of Cebu - Lapu-lapu & Mandaue',
                'University of Cebu - Maritime Education and Training Center',
                'University of Cebu - South Campus',
                "University of the Philippines Diliman - Main Campus",
                'University of Eastern Philippines - Catubig Campus, Northern Samar',
                'University of Iloilo',
                'University of the Immaculate Conception, Davao City',
                'University of La Salette',
                'University of La Salette - Main - Santiago City, Isabela',
                'University of La Salette - Roxas, Isabela',
                'University of La Salette - Aurora, Isabela',
                'University of La Salette - Quezon, Isabela',
                'University of La Salette - Cabatuan, Isabela',
                'University of La Salette - Ramon, Isabela',
                'University of La Salette - San Mateo, Isabela',
                'University of La Salette - Cordon, Isabela',
                'University of La Salette - Jones, Isabela',
                'University of Makati',
                'Universidad de Manila',
                'University of Manila',
                'University of Mindanao',
                'University of Mindanao - Main Campus (Bolton Street, Davao City)',
                'University of Mindanao - Main Campus (Matina, Davao City)',
                'University of Mindanao - Tagum Campus',
                'University of Mindanao - Digos Campus',
                'University of Mindanao - Penaplata Campus',
                'University of Mindanao - Guianga Campus',
                'University of Mindanao - Panabo Campus',
                'University of Mindanao - Bansalan Campus',
                'University of Mindanao - Cotabato Campus',
                'University of Mindanao - Toril Campus',
                'University of Mindanao - Bangoy Campus',
                'University of Mindanao - Tibungco Campus',
                'University of Negros Occidental - Recoletos',
                'University of Catbalogan City, Samar',
                'University of Northeastern Philippines',
                'University of Northern Philippines, Ilocos Sur',
                'University of Nueva Caceres',
                'University of Pangasinan',
                'University of Perpetual Help System',
                'University of Perpetual Help System DALTA',
                'University of Perpetual Help System JONELTA',
                'University of Rizal System',
                'University of Saint Anthony - San Miguel, Iriga City',
                'University of Saint Louis Tuguegarao, Cagayan',
                'University of San Agustin',
                'University of San Carlos - Main Campus',
                'University of San Carlos - South Campus',
                'University of San Carlos - North Campus',
                'University of San Carlos - Talamban Campus',
                'University of San Jose - Recoletos Main Campus - Magallanes St., Cebu City',
                'University of San Jose - Recoletos (Basak, Cebu Campus)',
                'University of San Jose - Recoletos (Arpili Balamban, Cebu Campus)',
                'University of Santo Tomas',
                'University of Southeastern Philippines',
                'University of Southern Mindanao',
                'University of Southern Philippines Foundation, Lahug Main Campus',
                'University of Southern Philippines Foundation, Mabini Campus',
                'University of the Assumption',
                'University of the Cordilleras',
                'University of the East',
                'University of the East, Caloocan',
                'University of the East, Manila',
                'UERMMMC, Quezon City',
                'University of the Immaculate Conception - Davao City',
                'University of the Philippines',
                'University of the Visayas, Cebu',
                'Urdaneta City University, Urdaneta City, Pangasinan',
                'Visayas State University Main Campus - Baybay City, Leyte',
                'Visayas State University - Tolosa, Leyte Campus',
                'Visayas State University - Alang-alang, Leyte Campus',
                'Visayas State University - Villaba, Leyte Campus',
                'Visayas State University - Isabel, Leyte Campus',
                'Western Mindanao State University',
                'Western Mindanao State University - Bayog',
                'Western Mindanao State University - Zamboanga City',
                'Western Mindanao State University - Molave',
                'Western Mindanao State University - Dumingag',
                'Western Mindanao State University - Malangas',
                'Wesleyan University-Philippines in Cabanatuan City',
                'Wesleyan University-Philippines (Aurora)',
                'Xavier University - Ateneo de Cagayan',
                'St. Mary\'s College of Baganga - Baganga, Davao Oriental'
            ],

            /**
             * Link : https://www.thesummitexpress.com/2025/05/full-list-2025-top-200-most-popular-universities-philippines.html
             */
            'SUC\'s of the Philippines' => [
                'University of the Philippines Diliman - Quezon City',
                'Polytechnic University of the Philippines - Manila',
                'Ateneo de Manila University - Quezon City',
                'De La Salle University - Manila',
                'University of the Philippines System - Quezon City',
                'University of Santo Tomas - Manila',
                'University of the Philippines Los Baños - Los Baños',
                'Ateneo de Davao University - Davao City',
                'University of the Philippines Manila - Manila',
                'Our Lady of Fatima University - Valenzuela City',
                'De La Salle-College of Saint Benilde - Manila',
                'University of San Carlos - Cebu City',
                'Xavier University-Ateneo de Cagayan - Cagayan de Oro City',
                'Batangas State University - Batangas City',
                'Mindanao State University - Iligan Institute of Technology, Iligan City',
                'Adamson University - Manila',
                'University of Southeastern Philippines - Davao City',
                'Silliman University - Dumaguete City',
                'Mapúa University - Manila',
                'Saint Louis University - Baguio City',
                'Ateneo de Naga University - Naga City',
                'Asian Institute of Management - Makati City',
                'University of Mindanao - Davao City',
                'Eastern Visayas State University - Tacloban City',
                'National University, Philippines - Manila',
                'Visayas State University - Baybay',
                'Far Eastern University - Manila',
                'University of San Jose-Recoletos - Cebu City',
                'Central Mindanao University - Maramag',
                'Technological University of the Philippines - Manila',
                'Central Philippine University - Iloilo City',
                'University of the Philippines in the Visayas - Iloilo City',
                'Adventist International Institute of Advanced Studies - Silang',
                'Cavite State University - Indang',
                'Lyceum of the Philippines University - Manila',
                'University of Asia and the Pacific - Pasig City',
                'New Era University - Quezon City',
                'University of Science and Technology of Southern Philippines - Cagayan de Oro City',
                'University of Cebu - Cebu City',
                'De La Salle Medical and Health Sciences Institute - Dasmariñas City',
                'University of the East - Manila',
                'University of Perpetual Help System DALTA - Las Piñas City',
                'Philippine Christian University - Manila',
                'Centro Escolar University - Manila',
                'University of Baguio - Baguio City',
                'University of the Philippines Baguio - Baguio City',
                'Bicol University - Legazpi City',
                'University of Batangas - Batangas City',
                'Ateneo de Zamboanga University - Zamboanga City',
                'Pamantasan ng Lungsod ng Maynila - Manila',
                'Miriam College - Quezon City',
                'University of Southern Mindanao - Kabacan',
                'Emilio Aguinaldo College - Manila',
                'Philippine Normal University - Manila',
                'Mariano Marcos State University - Batac',
                'De La Salle Lipa - Lipa City',
                'Western Mindanao State University - Zamboanga City',
                'Misamis University - Ozamiz City',
                'Technological Institute of the Philippines - Manila',
                'West Visayas State University - Iloilo City',
                'University of the Philippines Mindanao - Davao City',
                'Cebu Technological University - Cebu City',
                'Universidad de Zamboanga - Zamboanga City',
                'Mindanao State University - Marawi City',
                'Caraga State University - Butuan City',
                'Don Honorio Ventura Technological State University - Bacolor',
                'University of the Immaculate Conception - Davao City',
                'University of St. La Salle - Bacolod City',
                'Tarlac State University - Tarlac City',
                'Adventist University of the Philippines - Silang',
                'Angeles University Foundation - Angeles City',
                'Asia Pacific College - Makati City',
                'San Beda University - Manila',
                'University of Nueva Caceres - Naga City',
                'Central Luzon State University - Science City of Muñoz',
                'Holy Angel University - Angeles City',
                'University of the East Ramon Magsaysay - Quezon City',
                'John B. Lacson Foundation Maritime University - Iloilo City',
                'Sacred Heart College - Lucena City',
                'Cebu Normal University - Cebu City',
                'Saint Mary\'s University of Bayombong - Bayombong',
                'Manila Central University - Caloocan City',
                'Lorma Colleges - City of San Fernando',
                'Manuel S. Enverga University Foundation - Lucena City',
                'Bulacan State University - Malolos City',
                'Bohol Island State University - Bilar',
                'Cagayan State University - Tuguegarao City',
                'Benguet State University - La Trinidad',
                'FEU Institute of Technology - Manila',
                'Holy Cross of Davao College - Davao City',
                'Trinity University of Asia - Quezon City',
                'University of the Cordilleras - Baguio City',
                'University of Negros Occidental - Recoletos - Bacolod City',
                'Bataan Peninsula State University - Balanga City',
                'Cebu Institute of Technology - Cebu City',
                'Southern Leyte State University - Sogod',
                'Nueva Ecija University of Science and Technology - Cabanatuan City',
                'Chiang Kai Shek College - Manila',
                'José Rizal University - Mandaluyong City',
                'University of Saint Louis - Tuguegarao City',
                'Bukidnon State University - Malaybalay City',
                'Tarlac Agricultural University - Camiling',
                'Aquinas University of Legazpi - Legazpi City',
                'University of Perpetual Help System Jonelta - City of Biñan',
                'Pangasinan State University - Lingayen',
                'Don Mariano Marcos Memorial State University - Bacnotan',
                'AMA Computer University - Quezon City',
                'Colegio de San Juan de Letran - Manila',
                'The Philippine Women\'s University - Manila',
                'Aklan State University - Banga',
                'Rizal Technological University - Mandaluyong City',
                'Urdaneta City University - Urdaneta City',
                'National Defense College of the Philippines - Quezon City',
                'Davao Doctors College - Davao City',
                'Arellano University - Manila',
                'University of the Visayas - Cebu City',
                'Southwestern University - PHINMA - Cebu City',
                'Iloilo Science and Technology University - Iloilo City',
                'University of Bohol - Tagbilaran City',
                'St. Scholastica\'s College - Manila',
                'St. Paul University Philippines - Tuguegarao City',
                'Cebu Doctors\' University - Mandaue City',
                'Saint Jude College - Manila',
                'St. Luke\'s College of Medicine - WHQM - Quezon City',
                'Isabela State University - Echague',
                'Sultan Kudarat State University - Tacurong City',
                'Holy Name University - Tagbilaran City',
                'University of Northern Philippines - Vigan City',
                'University of San Agustin - Iloilo City',
                'Camarines Norte State College - Daet',
                'Camarines Sur Polytechnic Colleges - Nabua',
                'Manuel L. Quezon University - Quiapo',
                'Philippine School of Business Administration - Manila',
                'Palawan State University - Puerto Princesa City',
                'PATTS College of Aeronautics - Parañaque City',
                'Samar State University - Catbalogan City',
                'Mountain View College - Valencia City',
                'La Salle University - Ozamiz City - Ozamiz City',
                'University of the Assumption - City of San Fernando',
                'Capiz State University - Roxas City',
                'Assumption College San Lorenzo - Makati City',
                'Nueva Vizcaya State University - Bayombong',
                'Don Bosco Technical College - Mandaluyong City',
                'Universidad de Dagupan - Dagupan City',
                'Asian Institute of Journalism and Communication - San Juan',
                'Leyte Normal University - Tacloban City',
                'Northwestern University, Philippines - Laoag City',
                'Liceo de Cagayan University - Cagayan de Oro City',
                'Notre Dame of Marbel University - Koronadal City',
                'Laguna State Polytechnic University - Sta. Cruz',
                'St. Paul University Manila - Manila',
                'Father Saturnino Urios University - Butuan City',
                'Northwest Samar State University - Calbayog City',
                'University of Rizal System - Tanay',
                'Sorsogon State University - Sorsogon City',
                'Bulacan Agricultural State College - San Ildefonso',
                'Capitol University - Cagayan de Oro City',
                'Biliran Province State University - Biliran',
                'Cor Jesu College - Digos City',
                'Notre Dame of Dadiangas University - City of General Santos',
                'Ilocos Sur Polytechnic State College - Ilocos Sur',
                'Catanduanes State University - Virac',
                'National Teachers College - Manila',
                'Quirino State University - Diffun',
                'Asian Social Institute - Manila',
                'Central Colleges of the Philippines - Quezon City',
                'Aurora State College of Technology - Baler',
                'Negros Oriental State University - Dumaguete City',
                'North Eastern Mindanao State University - Tandag',
                'Wesleyan University-Philippines - Cabanatuan City',
                'University of Antique - Sibalom',
                'Universidad de Sta. Isabel - Naga City',
                'Eastern Samar State University - Borongan',
                'President Ramon Magsaysay State University - Iba',
                'Partido State University - Goa',
                'Saint Joseph Institute of Technology - Butuan City',
                'La Consolacion College Manila - Manila',
                'Filamer Christian University - Roxas City',
                'Western Philippines University - Aborlan',
                'La Consolacion University Philippines - Malolos City',
                'St. Paul University Quezon City - Quezon City',
                'Lyceum-Northwestern University - Dagupan City',
                'St. Paul University Iloilo - Iloilo City',
                'College of the Holy Spirit - Manila',
                'Virgen Milagrosa University Foundation - San Carlos City',
                'Southern Luzon State University - Lucban',
                'St. Paul University Dumaguete - Dumaguete City',
                'San Sebastian College-Recoletos de Cavite - Cavite City',
                'FEATI University - Manila',
                'Eulogio "Amang" Rodriguez Institute of Science and Technology - Sampaloc',
                'St. Paul University Surigao - Surigao City',
                'Guimaras State University - Buenavista',
                'Lourdes College - Cagayan de Oro City',
                'University of Iloilo - PHINMA - Iloilo City',
                'Aldersgate College - Solano',
                'Notre Dame University - Cotabato City',
                'National College of Business and Arts - Quezon City',
                'Baliuag University - Baliuag',
                'Araullo University - PHINMA - Cabanatuan City',
                'University of Pangasinan - PHINMA - Dagupan City',
                'Cebu Institute of Medicine - Cebu City',
                'University of Cagayan Valley - Tuguegarao City',
                'University of Southern Philippines Foundation - Cebu City',
                'Saint Michael\'s College of Laguna - Biñan City',
                'The University of Manila - Manila',
                'Central Philippine Adventist College - Murcia',
                'Saint Pedro Poveda College - Quezon City',
                'University of Luzon - Dagupan City',
                'Holy Trinity University - Puerto Princesa City',
                'Union Christian College - City of San Fernando',
                'Pasig Catholic College - Pasig City',
                'Zamboanga State College of Marine Sciences and Technology - Zamboanga City',
                'Romblon State University - Odiongan',
                'University of Eastern Philippines - Catarman, Northern Samar',
                'Abra State Institute of Science and Technology - Lagangilang',
                'Western Institute of Technology - Iloilo City',
                'Meycauayan College - Meycauayan City',
                'Olivarez College - Parañaque City',
                'STI West Negros University - Bacolod City',
                'University of La Salette - Santiago City',
                'Northern Luzon Adventist College - Pangasinan',
                'Marinduque State College - Boac',
                'Siena College of Taytay - Taytay',
                'Asian Institute of Maritime Studies - Pasay City',
                'Notre Dame of Kidapawan College - Kidapawan City',
                'St. Joseph\'s College of Quezon City - Quezon City',
                'St. Mary\'s College - Quezon City',
                'Republic Central Colleges - Angeles City',
                'St. Louis College Valenzuela - Valenzuela City',
                'Christ the King College - Calbayog City',
                'Santa Isabel College - Manila',
                'Guagua National Colleges - Guagua',
                'Misamis Oriental State College of Agriculture and Technology - Claveria',
                'Lipa City Colleges - Lipa City',
                'La Consolacion College - Iriga City'
            ]
        ];

        $this->renderWithoutLayout('auth/register', [
            'title' => 'Register - SUC Forum',
            'error' => $error,
            'success' => $success,
            'formData' => $formData,
            'universities' => $universities
        ]);
    }

    protected function renderWithoutLayout($view, $data = []) {
        extract($data);

        if (strpos($view, '/') !== false) {
            $parts = explode('/', $view, 2);
            $module = ucfirst($parts[0]);
            $viewFile = $parts[1];
            $viewPath = __DIR__ . "/../Views/{$viewFile}.php";
        } else {
            $viewPath = __DIR__ . "/../Views/{$view}.php";
        }

        if (file_exists($viewPath)) {
            include $viewPath;
        } else {
            throw new Exception("View not found: {$view}");
        }
    }
}
